---
language: node_js
node_js:
  - 8.9

dist: trusty

cache:
  npm: true

install:
  - npm install npm@5.5
  - npm install

script:
  - npm run lint

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
